### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by fkneist** [nightgrey/aether#1]
Hey,

I discovered the project on HN today, I'd love to host it, but I'm wondering what's the license?

**Comment by nightgrey** [comment]
Hey! We talked in DMs already. I added the license to the repo now (https://github.com/nightgrey/aether/blob/master/LICENSE), thanks for reaching out and good luck!

**Comment by 99991** [comment]
Note that the model used by this project also has a license agreement: https://bria.ai/bria-huggingface-model-license-agreement/
